# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'jekyll-sass-converter', '~> 2.0'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-optional-front-matter'
  gem 'jekyll-readme-index'
  gem 'jekyll-titles-from-headings'
  gem 'jekyll-relative-links'
  gem 'jekyll-theme-primer'
  gem 'jekyll-github-metadata'
  gem 'jekyll-default-layout'
end
